name: New Member Request
description: Requests to join a new code writers club
title: "Request to join from <USER>"
labels: ["new member"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Welcome! We are going to get you matched with a great group of people.
        
        First we need you to fill out a quick questionnaire. Don't worry, there are no wrong answers; feel free to skip any questions or add details not covered elsewhere that you think may help in matching you to a club.
        
        ## Getting to Know You
        Since this is a writers club, it would help to know what computer skills you can read or write. Please share what you hope to get out of the code writers club and what you think you can contribute to one. This will help us match you with a club that is similar enough you can participate while being diverse enough you can learn.
  - type: input
    id: known_languages
    attributes:
      label: What languages are you familiar with?
      placeholder: ex. Python, SQL, YAML
    validations:
      required: false
  - type: input
    id: wanted_languages
    attributes:
      label: What languages are you interested in?
      description: You can be an expert or novice in any of these.
      placeholder: ex. Forth, CSS, GraphQL
    validations:
      required: false
  - type: input
    id: known_skills
    attributes:
      label: What are some areas you consider yourself knowledgable in?
      description: Everyone has areas they are knowledgable in.
      placeholder: ex. fuzzy testing, docstring writing, web scraping
    validations:
      required: false
  - type: input
    id: wanted_skills
    attributes:
      label: What are some areas you would like to be exposed to?
      description: What do you want to come up during meets?
      placeholder: ex. ML models, games, Azure pipelines
    validations:
      required: false
   
  - type: markdown
    attributes:
      value: |
        ## Scheduling
        It is up to the individual clubs to set up a regular cadence and schedule meets. Let's try and get you a club that is similar to your availability.
  - type: input
    id: meeting_time
    attributes:
      label: When would you like to meet?
      placeholder: ex. week days, week nights, weekends
    validations:
      required: false
  - type: input
    id: meeting_frequency
    attributes:
      label: How often would you like to meet?
      placeholder: ex. weekly, monthly
    validations:
      required: false
  - type: input
    id: meeting_type
    attributes:
      label: How would you like to meet?
      placeholder: ex. in-person, virtually, maybe both
    validations:
      required: false
  - type: input
    id: tz
    attributes:
      label: What timezone are you in?
      description: Only necessary if you answered to meet virtually.
    validations:
      required: false
  - type: input
    id: locale
    attributes:
      label: Where are you located?
      description: Only necessary if you answered to meet in person.
    validations:
      required: false
  - type: checkboxes
    id: member_type
    attributes:
      label: "Are you interesed in being:"
      options:
        - label: a club leader
        - label: a club participant
    validations:
      required: false
  - type: textarea
    id: other
    attributes:
      label: Is there anything else you think we should know?
